# Generated by Django 6.0.2 on 2026-02-10 07:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('AGUS1', 'Agus 1'), ('AGUS2', 'Agus 2'), ('AGUS4', 'Agus 4'), ('AGUS5', 'Agus 5'), ('AGUS6', 'Agus 6'), ('AGUS7', 'Agus 7')], max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('capacity_mw', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=200)),
                ('commissioned_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'plants',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='plants_code_497880_idx'), models.Index(fields=['is_active'], name='plants_is_acti_3e91de_idx')],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('capacity_mw', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('commissioned_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='reports.plant')),
            ],
            options={
                'db_table': 'units',
                'ordering': ['plant', 'unit_number'],
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('records_imported', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('file_size', models.IntegerField()),
                ('checksum', models.CharField(max_length=64)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='reports.plant')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'uploaded_files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='GenerationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('generation_kwh', models.DecimalField(decimal_places=2, max_digits=15)),
                ('operating_hours', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('availability_hours', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('forced_outage_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('scheduled_outage_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('capacity_factor', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('availability_factor', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_reports', to='reports.plant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_reports', to='reports.unit')),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_reports', to='reports.uploadedfile')),
            ],
            options={
                'db_table': 'generation_reports',
                'ordering': ['-report_date', 'plant', 'unit'],
            },
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['plant', 'unit_number'], name='units_plant_i_a75aab_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['is_active'], name='units_is_acti_12026b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('plant', 'unit_number')},
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['plant', 'uploaded_at'], name='uploaded_fi_plant_i_7da83b_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['status'], name='uploaded_fi_status_e2833e_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['uploaded_by'], name='uploaded_fi_uploade_4163f5_idx'),
        ),
        migrations.AddIndex(
            model_name='generationreport',
            index=models.Index(fields=['plant', 'report_date'], name='generation__plant_i_b84bf1_idx'),
        ),
        migrations.AddIndex(
            model_name='generationreport',
            index=models.Index(fields=['report_date'], name='generation__report__e98887_idx'),
        ),
        migrations.AddIndex(
            model_name='generationreport',
            index=models.Index(fields=['unit', 'report_date'], name='generation__unit_id_3f5e9d_idx'),
        ),
        migrations.AddIndex(
            model_name='generationreport',
            index=models.Index(fields=['uploaded_file'], name='generation__uploade_6adefb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='generationreport',
            unique_together={('plant', 'unit', 'report_date')},
        ),
    ]
