# Generated by Django 5.2.11 on 2026-02-12 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_plantcapacity_historicaldata'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='historicaldata',
            new_name='historical__plant_i_823568_idx',
            old_name='historical_plant_i_idx',
        ),
        migrations.RenameIndex(
            model_name='historicaldata',
            new_name='historical__date_80140f_idx',
            old_name='historical_date_idx',
        ),
        migrations.RenameIndex(
            model_name='plantcapacity',
            new_name='plant_capac_plant_i_bb3598_idx',
            old_name='plant_capac_plant_i_idx',
        ),
    ]
