# Generated by Django 4.2.7 on 2026-02-19 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_add_user_roles_and_audit'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_user_id_88267f_idx',
            old_name='audit_logs_user_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_action_474804_idx',
            old_name='audit_logs_action_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_model_n_656046_idx',
            old_name='audit_logs_model_obj_idx',
        ),
        migrations.RenameIndex(
            model_name='userprofile',
            new_name='user_profil_role_fa03e1_idx',
            old_name='user_profil_role_idx',
        ),
        migrations.RenameIndex(
            model_name='userprofile',
            new_name='user_profil_plant_i_cbdfa2_idx',
            old_name='user_profil_plant_idx',
        ),
    ]
