# Generated by Django 4.2.7 on 2026-02-19 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_scheduled_reports'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reportexecution',
            new_name='report_exec_schedul_557b2e_idx',
            old_name='report_exec_schedul_idx',
        ),
        migrations.RenameIndex(
            model_name='reportexecution',
            new_name='report_exec_status_c1b883_idx',
            old_name='report_exec_status_idx',
        ),
        migrations.RenameIndex(
            model_name='scheduledreport',
            new_name='scheduled_r_status_5cae6f_idx',
            old_name='scheduled_r_status_idx',
        ),
        migrations.RenameIndex(
            model_name='scheduledreport',
            new_name='scheduled_r_frequen_98dc87_idx',
            old_name='scheduled_r_frequen_idx',
        ),
    ]
