# Generated by Django 4.2.7 on 2026-02-23 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_rename_report_exec_schedul_idx_report_exec_schedul_557b2e_idx_and_more'),
        ('reports', '0011_update_report_types_to_psr'),
    ]

    operations = [
    ]
