# Generated by Django 4.2.7 on 2026-02-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_merge_20260223_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='location',
            field=models.CharField(blank=True, help_text='Approximate location based on IP', max_length=200),
        ),
        migrations.AlterField(
            model_name='scheduledreport',
            name='report_type',
            field=models.CharField(choices=[('PSR', 'Plant Status Report (PSR)')], max_length=50),
        ),
    ]
