# Generated by Django 4.2.7 on 2026-02-26 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_add_archived_field'),
        ('reports', '0013_auditlog_location_alter_scheduledreport_report_type'),
    ]

    operations = [
    ]
