# Generated by Django 4.2.7 on 2026-03-11 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0015_password_reset_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signatory_name', models.CharField(help_text='Name of the person signing', max_length=100)),
                ('signatory_title', models.CharField(blank=True, help_text='Job title of the signatory', max_length=100)),
                ('signatory_role', models.CharField(blank=True, help_text="Role in the authorization (e.g., 'Prepared by', 'Approved by')", max_length=100)),
                ('signature_image', models.ImageField(help_text='Signature image file', upload_to='signatures/%Y/%m/')),
                ('signature_type', models.CharField(choices=[('DRAW', 'Hand Drawn'), ('UPLOAD', 'Uploaded Image'), ('TYPE', 'Typed Text')], default='DRAW', max_length=10)),
                ('signature_data', models.TextField(blank=True, help_text='Base64 encoded signature data for backup')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default signature for this signatory')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'e_signatures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(help_text='Date of the report')),
                ('report_type', models.CharField(default='PSR', help_text='Type of report (PSR, etc.)', max_length=50)),
                ('signatory_name', models.CharField(help_text='Name of the signatory', max_length=100)),
                ('signatory_role', models.CharField(help_text='Role in authorization', max_length=100)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('verification_hash', models.CharField(blank=True, help_text='Hash for signature verification', max_length=64)),
            ],
            options={
                'db_table': 'report_signatures',
                'ordering': ['-signed_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='passwordresetrequest',
            new_name='password_re_usernam_7c4f1c_idx',
            old_name='password_re_usernam_8a9c5f_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresetrequest',
            new_name='password_re_status_bfba9d_idx',
            old_name='password_re_status_2f4e8a_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresetrequest',
            new_name='password_re_created_556e6b_idx',
            old_name='password_re_created_1b7d3c_idx',
        ),
        migrations.RenameIndex(
            model_name='uploadedfile',
            new_name='uploaded_fi_is_arch_fddbc8_idx',
            old_name='uploaded_fi_is_arch_idx',
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportsignature',
            name='signature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_usages', to='reports.esignature'),
        ),
        migrations.AddField(
            model_name='reportsignature',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_signatures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='esignature',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_signatures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='reportsignature',
            index=models.Index(fields=['report_date', 'report_type'], name='report_sig_date_type_idx'),
        ),
        migrations.AddIndex(
            model_name='reportsignature',
            index=models.Index(fields=['signatory_name'], name='report_sig_name_idx'),
        ),
        migrations.AddIndex(
            model_name='reportsignature',
            index=models.Index(fields=['signed_by', 'signed_at'], name='report_sig_user_time_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reportsignature',
            unique_together={('report_date', 'report_type', 'signatory_name', 'signatory_role')},
        ),
        migrations.AddIndex(
            model_name='esignature',
            index=models.Index(fields=['signatory_name', 'is_active'], name='e_signature_signato_e7439d_idx'),
        ),
        migrations.AddIndex(
            model_name='esignature',
            index=models.Index(fields=['created_by'], name='e_signature_created_c95d76_idx'),
        ),
        migrations.AddIndex(
            model_name='esignature',
            index=models.Index(fields=['is_default', 'signatory_name'], name='e_signature_is_defa_74371a_idx'),
        ),
    ]
