# Generated by Django 4.2.7 on 2026-03-17 00:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0020_esignature_workflow_fixed'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='signatoryauthorization',
            name='unique_user_signatory',
        ),
        migrations.RenameIndex(
            model_name='signatoryauthorization',
            new_name='signatory_a_user_id_dcb842_idx',
            old_name='signatory_user_active_idx',
        ),
        migrations.RenameIndex(
            model_name='signatoryauthorization',
            new_name='signatory_a_signato_453ac3_idx',
            old_name='signatory_name_active_idx',
        ),
        migrations.RenameIndex(
            model_name='signatoryauthorizationrequest',
            new_name='signatory_a_user_id_7ea3cc_idx',
            old_name='auth_req_user_status_idx',
        ),
        migrations.RenameIndex(
            model_name='signatoryauthorizationrequest',
            new_name='signatory_a_status_31c668_idx',
            old_name='auth_req_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='signatoryauthorizationrequest',
            new_name='signatory_a_signato_ae179b_idx',
            old_name='auth_req_signatory_idx',
        ),
        migrations.RenameIndex(
            model_name='signaturerequest',
            new_name='signature_r_token_fd8c2d_idx',
            old_name='signature_r_token_b8e5a5_idx',
        ),
        migrations.RenameIndex(
            model_name='signaturerequest',
            new_name='signature_r_status_259561_idx',
            old_name='signature_r_status_4a8b9c_idx',
        ),
        migrations.RenameIndex(
            model_name='signatureverificationtoken',
            new_name='signature_v_user_id_4bcdb3_idx',
            old_name='sig_token_user_used_idx',
        ),
        migrations.RenameIndex(
            model_name='signatureverificationtoken',
            new_name='signature_v_token_92928e_idx',
            old_name='sig_token_token_used_idx',
        ),
        migrations.RenameIndex(
            model_name='signatureverificationtoken',
            new_name='signature_v_expires_35c071_idx',
            old_name='sig_token_expires_idx',
        ),
        migrations.RemoveField(
            model_name='esignature',
            name='verification_hash',
        ),
        migrations.AlterField(
            model_name='signatoryauthorizationrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='signatoryauthorization',
            unique_together={('user', 'signatory_name')},
        ),
    ]
