# Generated by Django 4.2.7 on 2026-03-17 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0022_add_signature_setup_token'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='signatoryauthorization',
            new_name='signatory_a_setup_t_76cc57_idx',
            old_name='reports_sig_setup_token_idx',
        ),
    ]
