# Generated by Django 4.2.7 on 2026-03-18 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0021_enhanced_audit_logs'),
        ('reports', '0023_rename_reports_sig_setup_token_idx_signatory_a_setup_t_76cc57_idx'),
    ]

    operations = [
    ]
