# Generated by Django 4.2.7 on 2026-04-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0025_fix_audit_log_session_key'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_ip_addr_932507_idx',
            old_name='reports_auditlog_ip_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_categor_0633bd_idx',
            old_name='reports_auditlog_category_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_severit_549d29_idx',
            old_name='reports_auditlog_severity_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_success_05986f_idx',
            old_name='reports_auditlog_success_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_url_pat_292ed4_idx',
            old_name='reports_auditlog_url_path_idx',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('LOGIN_FAILED', 'Failed Login Attempt'), ('PASSWORD_CHANGE', 'Password Changed'), ('PASSWORD_RESET_REQUEST', 'Password Reset Requested'), ('PASSWORD_RESET_COMPLETE', 'Password Reset Completed'), ('USER_CREATE', 'User Created'), ('USER_UPDATE', 'User Updated'), ('USER_DELETE', 'User Deleted'), ('USER_ACTIVATE', 'User Activated'), ('USER_DEACTIVATE', 'User Deactivated'), ('FILE_UPLOAD', 'File Uploaded'), ('FILE_DOWNLOAD', 'File Downloaded'), ('FILE_DELETE', 'File Deleted'), ('FILE_ARCHIVE', 'File Archived'), ('FILE_RESTORE', 'File Restored'), ('FILE_VIEW', 'File Viewed'), ('FILE_EXPORT', 'File Exported'), ('REPORT_GENERATE', 'Report Generated'), ('REPORT_PREVIEW', 'Report Previewed'), ('REPORT_VIEW', 'Report Viewed'), ('REPORT_EXPORT', 'Report Exported'), ('REPORT_DELETE', 'Report Deleted'), ('REPORT_SIGN', 'Report Signed'), ('SIGNATURE_CREATE', 'E-Signature Created'), ('SIGNATURE_UPDATE', 'E-Signature Updated'), ('SIGNATURE_DELETE', 'E-Signature Deleted'), ('SIGNATURE_VIEW', 'E-Signature Viewed'), ('SIGNATURE_SETUP_ACCESS', 'Signature Setup Page Accessed'), ('SIGNATURE_SETUP_COMPLETE', 'Signature Setup Completed'), ('AUTH_REQUEST_CREATE', 'Authorization Request Created'), ('AUTH_REQUEST_APPROVE', 'Authorization Request Approved'), ('AUTH_REQUEST_REJECT', 'Authorization Request Rejected'), ('AUTH_REQUEST_CANCEL', 'Authorization Request Cancelled'), ('AUTH_REQUEST_VIEW', 'Authorization Request Viewed'), ('AUTH_GRANT', 'Authorization Granted'), ('AUTH_REVOKE', 'Authorization Revoked'), ('AUTH_APPROVE_EXISTING', 'Authorization Approved with Existing Signature'), ('DATA_CREATE', 'Data Created'), ('DATA_UPDATE', 'Data Updated'), ('DATA_DELETE', 'Data Deleted'), ('DATA_VIEW', 'Data Viewed'), ('DATA_SEARCH', 'Data Searched'), ('DATA_FILTER', 'Data Filtered'), ('DATA_SORT', 'Data Sorted'), ('DOCUMENT_CREATE', 'Document Created / Saved'), ('DOCUMENT_UPDATE', 'Document Updated'), ('DOCUMENT_DELETE', 'Document Deleted'), ('DOCUMENT_VIEW', 'Document Viewed'), ('SYSTEM_BACKUP', 'System Backup'), ('SYSTEM_RESTORE', 'System Restore'), ('SYSTEM_MAINTENANCE', 'System Maintenance'), ('SYSTEM_CONFIG_CHANGE', 'System Configuration Changed'), ('SYSTEM_ERROR', 'System Error'), ('PAGE_ACCESS', 'Page Accessed'), ('DASHBOARD_VIEW', 'Dashboard Viewed'), ('MENU_NAVIGATE', 'Menu Navigation'), ('COMPONENT_LOAD', 'Component Loaded'), ('EMAIL_SENT', 'Email Sent'), ('EMAIL_FAILED', 'Email Failed'), ('EMAIL_LINK_CLICKED', 'Email Link Clicked'), ('SECURITY_VIOLATION', 'Security Violation'), ('UNAUTHORIZED_ACCESS', 'Unauthorized Access Attempt'), ('PERMISSION_DENIED', 'Permission Denied'), ('TOKEN_EXPIRED', 'Token Expired'), ('TOKEN_INVALID', 'Invalid Token Used'), ('API_CALL', 'API Call Made'), ('API_ERROR', 'API Error'), ('API_RATE_LIMIT', 'API Rate Limit Hit'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('UPLOAD', 'Upload'), ('EXPORT', 'Export'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('VIEW', 'View'), ('ACCESS', 'Access')], max_length=30),
        ),
    ]
