# Generated by Django 4.2.7 on 2026-04-20 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0027_monthly_targets'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='monthlytarget',
            name='unique_plant_year_month_target',
        ),
        migrations.RenameIndex(
            model_name='monthlytarget',
            new_name='monthly_tar_plant_i_b88b66_idx',
            old_name='monthly_targets_plant_year_month_idx',
        ),
        migrations.RenameIndex(
            model_name='monthlytarget',
            new_name='monthly_tar_year_6fd850_idx',
            old_name='monthly_targets_year_month_idx',
        ),
        migrations.AlterUniqueTogether(
            name='monthlytarget',
            unique_together={('plant', 'year', 'month')},
        ),
    ]
